name: VSCE CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Set up Haxelib dependencies
        run: |
          haxelib install vscode --quiet
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present
        env:
          CI: true
